categories: [Statistics]
description: This tool calculates row mean values for a table of numerics
long_description: Calculates means of each row of a table of numeric data
name: row_means
owner: simon-gladman
